### ISSUE TITLE
Create new site locale

### ISSUE THREAD

**Issue by phildexter** [wagtail/wagtail-localize#130]

**Comment by phildexter** [comment]
> Creating a new site-locale
> A new site-locale is created from the Locales page in Settings. A locale and a source site-locale has to be selected.
> Upon creation, Wagtail creates the full site tree so that the destination and source locales have the same structure. At this stage the destination pages are showing the untranslated content by default (as no translations have occurred). It also matches the publishing state of the source page, so most pages will immediately be published.
> Technically, these pages are created as Alias Pages - placeholders that mirror the source page’s content and state (published / draft). If a user tries to edit one, they will be asked if they want to translate that page. If they do, a translated page is created. If not, they are unable to edit anything.
>

**Comment by phildexter** [comment]
- [ ] Copy page optimisations (30m)
- [ ] Locale components test (2h)
- [ ] Locale components docs (2h)
- [ ] Alias pages tests (2h)
- [ ] Alias pages docs (2h)
- [ ] UI for Alias into regular page (1h) (click here to change to regular page + confirmation, link to page it's an alias of)
- [ ] UI for alias into translated page - instead of showing turn this into regular page, show turn this into translated page.

Leave audit logging out, include as a future feature (esp with audit logging refactoring)

**Comment by kaedroho** [comment]
All unit tests added now. Just waiting for review on https://github.com/wagtail/wagtail-localize/pull/191 then we can close!
