### ISSUE TITLE
Page edit - Page validation error states

### ISSUE THREAD

**Issue by phildexter** [wagtail/wagtail-localize#161]
database level error states (e.g. field length too long, or text instead of number)

**Comment by phildexter** [comment]
When there are errors we still let publish happen but rather than "Successfully published 'Breads' in French", we will say "'Breads' published but with translations missing - see below".

**Comment by kaedroho** [comment]
This is deployed now. I also fixed that bug where it wasn't reporting the field error

**Comment by phildexter** [comment]
When I have a title that is too long it now gets a 500 server error when I try and publish instead of catching it and telling me there is an issue....
