### ISSUE TITLE
Single quote characters are converted in translation fields and .po files

### ISSUE THREAD

**Issue by TheoChevalier** [wagtail/wagtail-localize#165]
There’s an example here, the source contains a single quote `'` in the very last field of the page, and in the French page, it appears as `&#x27;`

https://localize-workflow-develop.herokuapp.com/admin/pages/108/edit/

![image](https://user-images.githubusercontent.com/1294206/90768324-70243d00-e2e6-11ea-8568-88087b47366e.png)

I think we just need to convert them back, and escape them in the .po files using `\` I assume the .po processor should already be able to handle these cases

**Comment by kaedroho** [comment]
Thanks for spotting, hopefully this will have been fixed by https://github.com/wagtail/wagtail-localize/pull/163 (deploying now)
