### ISSUE TITLE
Create / Edit Locale

### ISSUE THREAD

**Issue by phildexter** [wagtail/wagtail-localize#213]
- A locale shouldn't be able to sync from itself.
- Make the "sync from" non editable on the UI once a locale has been created.

**Comment by HsnVahedi** [comment]
What does this field (sync from) do?

Sorry, I'm kind of newbie!

**Comment by phildexter** [comment]
Hi @HsnVahedi .

Sync from is a field you choose when you setup a new locale that is being translated to. It's the locale that you want the new locale to be translated from.

For instance, if I have a site which is English, but I now want to translate it into Spanish, I would create a new locale, called Spanish.

In this instance, I would choose "English" in the Sync From field.

However, if I then wanted to have a Guatemalan-Spanish translation of the same site, I might want that translation to come from my Spanish one, to my Guatemalan-Spanish one (as it's easier to translate from Spanish to Guatemalan-Spanish than it is to translate from English to Guatemalan-Spanish.

So in this instance I would create a new locale called "Guatemalan-Spanish", and I would choose "Spanish" in the sync from field.

With this setup it means translations are effectively going: English ->Spanish->Guatemalan-Spanish

**Comment by phildexter** [comment]
As well as the above, Sync From also sets the "Default" page structure and content that you new site will inherit. So when you very first create your new translated site, if you've chosen English as your sync from, then the site will essentially be an exact copy of your english site, waiting for the translations to happen (same content, same pages etc).

**Comment by HsnVahedi** [comment]
Thanks! That's really smart!
