### ISSUE TITLE
Translatable ListBlock

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail-localize#22]
We can't make `ListBlock` translatable because we need a way to uniquely identify blocks on different translations of a page while not being sensitive to ordering changes, deleting and adding new items.

The best alternative at the moment is to use a `StreamBlock` with a single block type, but the UI for this isn't very nice.

We can probably come up with a replacement for `ListBlock` that has the exact same UI and API, but the database representation is a list of objects with ``uuid`` and ``value`` keys.

**Comment by kaedroho** [comment]
Just a note to say that we have a plan to improve ``ListBlock`` inside Wagtail itself to include an ID for each item

**Comment by kaedroho** [comment]
RFC for adding UUIDs to `ListBlock` submitted here: https://github.com/wagtail/rfcs/pull/65

**Comment by kaedroho** [comment]
Getting closer to a fix for this now: https://github.com/wagtail/wagtail/pull/7741

**Comment by vladox** [comment]
@kaedroho do you have an estimation on when the PR will be released?

**Comment by zerolab** [comment]
@vladox the aim is to get https://github.com/wagtail/wagtail/pull/7741/ in Wagtail 2.16, dependant on code review -- would help if you could test those changes with a local codebase.

Once it makes it in an official Wagtail release, we can proceed with this issue
