### ISSUE TITLE
pypi version not up-to-date

### ISSUE THREAD

**Issue by Syltas** [wagtail/wagtail-localize#223]
Hey together,
running pip install wagtail-localize will downgrade Django to 2.2.17 and Wagtail to 2.7.4
This is especially problematic as wagtail-localize is now the officially supported wagtail localization package since version 2.11
I would be very happy if you could update the pypi package, thanks a lot! (:

**Comment by kaedroho** [comment]
I've pushed version 0.9 to pypi now, consider this a preview of the final release that will come in the next couple of weeks.

This is missing a few features:

- The ability to override untranslatable fields (like images)
- See linked translatable snippets from the editor
- Create a new locale tree using alias pages

**Comment by Syltas** [comment]
Awesome, thank you! Can't wait to test it out :D
