### ISSUE TITLE
wagtail-localize.js not found

### ISSUE THREAD

**Issue by naglis** [wagtail/wagtail-localize#225]
I am testing 0.9 (thanks for the effort!) and when trying to translate (i.e. edit a page not in the main language) a page, the editor does not load (blank page). In the console I get a 404 on `/static/wagtail_localize/js/wagtail-localize.js`. I've checked [the *.whl for 0.9](https://files.pythonhosted.org/packages/93/69/22f545eb027431285ce13a2eab0fec7385600b3cc76761cecc7d15c31f3d/wagtail_localize-0.9-py3-none-any.whl) and the `/static` dir seems empty. Do I need some extra steps to transpile TypeScript in `static_src`?

Sorry if this is a noob question and please let me know if additional information is needed to debug it.

**Comment by kaedroho** [comment]
Oops! Sorry I messed up the packaging. Please try version 0.9.1 that's just been released!

**Comment by naglis** [comment]
It works with 0.9.1! :tada: Wow, thank you for such a quick response :1st_place_medal:

**Comment by kaedroho** [comment]
No problem, thanks for the report!
