### ISSUE TITLE
Link one site to multiple roots with different languages

### ISSUE THREAD

**Issue by Warqus** [wagtail/wagtail-localize#229]
I want to create one site that links to multiple language roots. How can I do this?

I posted this question on Wagtail support in the Slack channel, but no one answered it.. Since it is related with multi language support, I would love to get an answer to the above question.

Thanks!

**Comment by kaedroho** [comment]
There's some documentation in Wagtail core on how to create links between multiple languages here: https://docs.wagtail.io/en/stable/advanced_topics/i18n.html?highlight=internationalisation#language-region-selector

**Comment by Warqus** [comment]
@kaedroho Thanks for reacting. I know how it works in the frontend. The thing is, I want to create example.com as a site in the multi-site section of the CMS, with example.com linking to multiple language roots.

The result will be that whenever I use the CMS api with ORIGIN example.com/api/pages/1?locale=en, I get the english translation of the page. Whenever I use ?locale=nl, it will give me the dutch version of the page. Is this possible?

**Comment by kaedroho** [comment]
> The result will be that whenever I use the CMS api with ORIGIN example.com/api/pages/1?locale=en, I get the english translation of the page. Whenever I use ?locale=nl, it will give me the dutch version of the page. Is this possible?

The Dutch translation would have a different page ID to the English one. You can find the IDs of the translations by requesting the `translations` field: `example.com/api/pages/1/?fields=translations`. This should add a list of translated pages into the ``meta.translations`` key on the page.

**Comment by Warqus** [comment]
I'll try that out, thanks!
