### ISSUE TITLE
[feature request] Add language to snippet chooser

### ISSUE THREAD

**Issue by ghost** [wagtail/wagtail-localize#235]
Currently if you translate a snippet, they will have the same name. When choosing a snippet within a page (with the SnippetChooser), I cannot see the language of the snippets.

![image](https://user-images.githubusercontent.com/14151318/98564884-380d1480-22ad-11eb-9b04-eaee02a08f64.png)

In the above image, one snippet is English, the other one is Dutch.

It would be nice to get a dropdown of the available languages to display only the snippets in the selected language.
Another possibility would be showing only the snippets in the language of the current page you are adding your snippet to.

**Comment by kaedroho** [comment]
Implementation started in https://github.com/wagtail/wagtail/pull/6230

Just needs tests!

**Comment by zerolab** [comment]
Done in https://github.com/wagtail/wagtail/pull/6699
