### ISSUE TITLE
Pipenv locking error

### ISSUE THREAD

**Issue by Shaffle1** [wagtail/wagtail-localize#239]
When trying to upgrade or install `wagtail-localize` with `pipenv`, it errors on locking dependencies(wagtail)

![image](https://user-images.githubusercontent.com/23004287/98839513-e6e45880-2445-11eb-9994-25af969569f8.png)

`pipenv lock --clear` did not work.

I think it should be just `wagtail>=2.10,<2.11`. Otherwise, I think `pipenv` can not find matching version of `wagtail`

**Comment by kaedroho** [comment]
Wagtail Localize requires Wagtail 2.11. I'm not that familiar with Pipenv so not sure why there's a ``wagtail<2.11`` restriction in there too.

Anyhow, this doesn't sound like a ``wagtail-localize`` issue because the value in ``setup.py`` is correct. But thanks for checking1
