### ISSUE TITLE
TranslatableTabbedInterface?

### ISSUE THREAD

**Issue by Shaffle1** [wagtail/wagtail-localize#241]
Hey! Kind of feature request. I love to organize fields with tabs. And also I use InlinePanels a lot, so the question is will there be separate `TranslatableTabbedInterface`, `TranslatableInlinePanel` and `TabbedInterface`, `InlinePanel`, which I will have to use both on all of the pages or in future it will be somehow combined? I think these features will be appreciated by a lot of people. How soon will they be done?

**Comment by kaedroho** [comment]
Hey @Shaffle1

Sorry if I've misunderstood you request. Wagtail Localize uses separate pages for translation, you can already translate fields in ``TabbedInterface`` and ``InlinePanel``.

**Comment by Shaffle1** [comment]
Oh, sorry. Really looking forward to the documentation! Could you quickly explain to me how? When I click on `Translate the page`, tranlated pages do not show any `Tabs` or `InlinePanels`, do I need to change the Panel types?
