### ISSUE TITLE
Order of fields in editor for translated pages

### ISSUE THREAD

**Issue by gibbsmaya** [wagtail/wagtail-localize#247]
The order of fields in the editor for translated pages follows the order in which they are defined on the model, rather than being configurable as they are in non-translated pages (using the `content_panels` model attribute).

Is there a way for wagtail-localize to provide a way to tailor this order, the way `content_panels` does in vanilla Wagtail?

**Comment by kaedroho** [comment]
Thanks for reportin @gibbsmaya!

Right now, the order is defined by the ``translatable_fields`` attribute on the model. but if this isn't specified, ``wagtail-localize`` will automatically this from the model. So you could change the ordering by defining ``translatable_fields`` with the same configs that are auto-generated but in put the fields in a different order.

You can find the auto-generated configs by running the following in the shell:

```python
>>> from wagtail_localize.fields import get_translatable_fields
>>> from myapp.models import MyPage
>>> get_translatable_fields(MyPage)
```

But I do agree that these should follow the ordering of ``content_panels`` (on this view only), so leaving this issue open to change that.

**Comment by gibbsmaya** [comment]
Thanks @kaedroho .

Once that is changed, does that mean it will follow the same order as the non-translated page or will you need to set the ordering for the translated page using the content-panels attribute separately?

**Comment by kaedroho** [comment]
Yep, once that's changed, it will follow the order of the non-translated page (you will need to "Sync Translations" though). Both pages use the same type so have the same ``content_panels`` (localize ignores this in its own view of the page).
