### ISSUE TITLE
Translatable snippets not showing up

### ISSUE THREAD

**Issue by Syltas** [wagtail/wagtail-localize#250]
Hey there 
Similar to Kalob's tutorial I added categories, tags and authors to my blog. I made category and blog author translatable and added them into the blogpage as translatable fields. Everything works fine but when I try to edit the translation neither authors nor categories nor blog tags are showing up to be translated. Is the translation of these snippets inserted automatically or am I doing something wrong here?

**Comment by Shaffle1** [comment]
+1
Also using `SnippetChooserPanel` when translating any page, the translation of the `SnippetChooserPanel` is the name of chosen snippet, I think `SnippetChooserPanel` should be choosable but still synchronized same as `PageChooserPanel` now.

Also it will be nice to have if `SnippetChooserPanel` had an option to only allow to choose snippets in the same locale as the "now translating" page. I mentioned this in #267 for `PageChooserPanel` too.
