### ISSUE TITLE
Having a non-translatable snippet breaks edit/create of this snippet

### ISSUE THREAD

**Issue by murray3k** [wagtail/wagtail-localize#265]
### The Problem
`AttributeError: 'NoneType' object has no attribute 'is_shown'` in
`wagtail\snippets\action_menu.py", line 122, in <listcomp>`
This function `get_base_snippet_action_menu_items(self.context['model'])` there returns a list, which is not check for `None` elements. But **wagtail-localize** introduces a `None` there through a hook that cause the AttributeError.

### How to reproduce:

Just having a snippets which doesn't inherit from `TranslatableMixin` is enough. Now, one can no edit or create this snippet.
```python
@register_snippet
class Foo(models.Model):
    name = models.CharField(max_length=255)
    panels = [
        FieldPanel('name')
    ]

    def __str__(self):
        return self.name
````

### Solution
This is should be fixed in the wagtail source, but **wagtail-localize** is causing it through this hook:
```python
@hooks.register("register_snippet_action_menu_item")
    def register_restart_translation_snippet_action_menu_item(model):
        if issubclass(model, TranslatableMixin):
            return RestartTranslationSnippetActionMenuItem(order=0)
````
This returns `None` when `TranslatableMixin` is not a parent class, therefore introducing the `None` from above.
Wagtail should check if this hook returns `None`. I will leave an issue there, referencing this one.

### Hotfix
Return a dummy object where `is_shown` is always `False` in the else-clause.

**Comment by kaedroho** [comment]
Fixed by #257
