### ISSUE TITLE
sync translated pages seems not to work properly

### ISSUE THREAD

**Issue by glanzel** [wagtail/wagtail-localize#266]
When i add a change to the source page after start translation,
the changes seems not to mirror to the translated opage

What i did:
Add a Page "news" to the englisch page Tree.
Add some content. "now with even more news"
Select another language ('es') to translate the "News" page.

go back to the english news page and add some more content.
Hit, "sync translated pages" in "News" Dropdown.
open the spanish news page again.
the "now with even more news" tag does not show up.

**Comment by patillacode** [comment]
Hi @glanzel 

The same thing happened to me, but I don't think this is a bug.

Pages will sync when published, so if you make the change in the English version and publish it and then hit "sync" you will see the change in the Spanish version. I believe only published pages can be synced.
Can you confirm on your case?

I can see why we could maybe take advantage from having drafts being synced, but I am not certain it fits the "generic approach" Wagtail has to maintain.

As for any active Wagtail developer reading this, what do you think of having the possibility of syncing drafts too?
Also, is the current behaviour expected? Could we get some deeper insights as to why? Only if possible.

**Comment by glanzel** [comment]
Okay you are right. I missed that i had to do both publish and then hit sync.
I think it could be more easy if you don't need to hit two buttons, but I am happy that its works now.

Thanks very much
