### ISSUE TITLE
Page fields don't get updated when syncing from a locale.

### ISSUE THREAD

**Issue by HsnVahedi** [wagtail/wagtail-localize#285]
### Steps to produce:

1. Define HomePage like this:
```
class HomePage(Page):
    field_a = models.TextField(default='')
    content_panels = Page.content_panels + [FieldPanel('field_a')]
```

2. Migrate.
3. Create a new Locale syncing from the default locale. (for example create locale "fr" syncing from "en")
4. Now try to edit the created `fr` page. As you can see, It prompts you to translate fields: [`title`, `field_a`]
5. Add another field to HomePage and migrate the database:
```
class HomePage(Page):
    field_a = models.TextField(default='')
    field_b = models.TextField(defalut='')
    content_panels = Page.content_panels + [FieldPanel('field_a'), FieldPanel('field_b')]
```
6. Now create another locale syncing from the default language. (for example create locale "de" syncing from "en")
7. Try to edit the created `de` page. It prompts you to translate fields:  [`title`, `field_a`] and not `field_b`.

As you can see the added `field_b` is not provided for translation.

This is a bug because it makes it impossible to translate the page.

**Comment by kaedroho** [comment]
When you add a new field, you need to go back to the source page in the page explorer and click on "Sync translated pages" in the more menu to make it push through content of the new field.

Also, if the field has no content, it won't be shown in the translation UI.

Does the new field have content? Did you run "Sync translated pages"?

**Comment by HsnVahedi** [comment]
Thanks a lot! @kaedroho

My bad! I had not run "Sync translation pages"

Running it solved my problem.
