### ISSUE TITLE
Machine translation compatibility

### ISSUE THREAD

**Issue by Lukaa0** [wagtail/wagtail-localize#290]
Hello is it possible to use other machine translation framework like Gtranslate?

**Comment by kaedroho** [comment]
Yes it is, you need to create a subclass of ``BaseMachineTranslator`` for it and implement the methods, for example: https://github.com/wagtail/wagtail-localize/blob/master/wagtail_localize/machine_translators/deepl.py

Once you've done that, you can point ``WAGTAILLOCALIZE_MACHINE_TRANSLATOR ['CLASS']`` at your class.
