### ISSUE TITLE
Is it possible to hide translation trees

### ISSUE THREAD

**Issue by ArthurConan** [wagtail/wagtail-localize#293]
Sorry, if this question is stupid,  but I wonder  - is it possible to see only the tree of the canonical language, with **an edit** in button where they can choose the language to edit the page in. 

something like WAGTAILTRANS_HIDE_TRANSLATION_TREES in _**wagtailtrans**_ lib ? 

thanks!

**Comment by kaedroho** [comment]
This isn't supported at the moment, out of interest what benefit do you think an interface like this would have over having the ability to see the page tree in different languages?

**Comment by ArthurConan** [comment]
For example, I have 5 diff languages and 10 different pages
And pages menu is inconvenient. It has:
Home (english)
Home (chinese)
Home (russian) 
...
and so on for 10*5 pages.

Maybe I posed a question in a wrong way - I am sorry - I just wonder is it possible to hide pages (all except admin chosen language) or just group pages into folder - Home (will have all home pages) Contacts and so on for all 10 diff pages.

Thanks!

**Comment by kaedroho** [comment]
There's a [PR](https://github.com/wagtail/wagtail/pull/6489) waiting for review on Wagtail core that adds a locale filter to the top level of the page menu. so that you can quickly hide all but one language. Do you think this will help?

**Comment by ArthurConan** [comment]
Sounds great!
Thanks
