### ISSUE TITLE
Subsequently added models not shown on translated pages 

### ISSUE THREAD

**Issue by andre-fuchs** [wagtail/wagtail-localize#314]
### Steps to reproduce

Add a new field to a page, that you already have published and translated before. After migration this new field is usable as usual in the default language page. But it gets not shown on the translated page. Do I have to define everything beforehand? Seems hard to believe. Sorry in advance, if I miss something obvious here.

**Comment by kaedroho** [comment]
Hi @andre-fuchs

You have to resubmit the page after you make a model change to it. Perhaps we could detect this and show a warning to the user if they are editing translations that were generated on an older version of the model
