### ISSUE TITLE
Creating a locale with wagtail_localize.locales app forces a total sync

### ISSUE THREAD

**Issue by patillacode** [wagtail/wagtail-localize#316]
When we try to create a locale through the admin using `wagtail_localize.locales` in `INSTALLED_APPS` the `Sync from` field seems to be required when it should not be.

![Screenshot 2021-02-02 at 15 19 05](https://user-images.githubusercontent.com/10074977/106637310-ce866480-6582-11eb-9b0c-0d99d6fb186a.png)

(This was created in reference to #315 )

**Comment by andre-fuchs** [comment]
This was mentioned here, too:

#313
