### ISSUE TITLE
Compatibility with Wagtail 2.12

### ISSUE THREAD

**Issue by patillacode** [wagtail/wagtail-localize#320]
Hi, 

couple of quick ones,

Is there an ETA or even a process in place for making `wagtail-localize` compatible with `Wagtail 2.12`?

Since I am asking about releases, do you have any expected timeframes for a `1.0` version of `wagtail-localize`?

**Comment by kaedroho** [comment]
Thanks, @patillacode!

I have some time for localize coming up later this month, I will look into this issue then. Hopefully also have enough time to finish off the initial release (or at least, get it much closer).

The work remaining is:
 - Finishing the initial documentation
 - Adding a report
 - Fixing some bugs
