### ISSUE TITLE
Inlines trigger error upon save

### ISSUE THREAD

**Issue by jkoestinger** [wagtail/wagtail-localize#346]
Hi, first thank you for the work on this project

I tried to implement the base example for the form builder (provided there: https://docs.wagtail.io/en/latest/reference/contrib/forms/#usage) and I ran into the following issue:

- The FormField is not translatable, so it does not show in the translated page, that's expected
- If I add the TranslatableMixin to the FormField, I get the following error when saving the original page:
![Capture d’écran 2021-02-23 à 14 55 10](https://user-images.githubusercontent.com/5838342/108853616-3ad70f80-75e7-11eb-8c1d-923c783a5d82.png)

Is there something that I missed? Also, I'm not 100% sure whether it concerns this project or the Wagtail project directly

**Comment by kaedroho** [comment]
Hi @jkoestinger 

If you're adding ``TranslatableMixin`` to a model with existing data Django will try to assign the same UUID to every value in the model causing an error like this.

The way to solve this is to use the ``BootstrapTranslatableMixin`` method described in https://docs.wagtail.io/en/stable/advanced_topics/i18n.html#making-snippets-with-existing-data-translatable

The title "Making *snippets* with existing data translatable" is a little misleading as it applies to child objects too, I'll fix that!

**Comment by jkoestinger** [comment]
Hi, thanks for your response.

Sorry, my initial message was unclear: I actually removed the model directly before adding the mixing, so I think the `BootstrapTranslatableMixin` step should not be needed in this case, right?

**Comment by kaedroho** [comment]
Yep, that's correct. I'll see if I can replicate this locally, thanks for reporting!
