### ISSUE TITLE
README.md says it supports up to wagail 2.11, is it wrong?

### ISSUE THREAD

**Issue by perepicornell** [wagtail/wagtail-localize#354]
I didn't update to wagtail 2.12 because of that but now I just saw that here: https://www.wagtail-localize.org/ it says it supports 2.11 and 2.12.

**Comment by vladox** [comment]
Wagtail 2.12.2 is giving a dependency error on install ```wagtail-localize==0.9.4   requires Django<3.2,>=2.2, polib<2.0,>=1.1, Wagtail<2.12,>=2.11```, apparently master has a fix but is not released yet.
When do you plan to release version 0.9.5?

**Comment by kaedroho** [comment]
Just pushed 0.9.5, sorry for the delay!

**Comment by vladox** [comment]
@kaedroho awesome, thanks for your help!

**Comment by perepicornell** [comment]
Cool! Thank you!!
