### ISSUE TITLE
Setting for not integrating in the page-model

### ISSUE THREAD

**Issue by rokondo** [wagtail/wagtail-localize#401]
I am new to wagtail and all this stuff, but I decided that I do not want the page nested as tree to translate them and choose for this part the `wagtail-modeltranslation`. But to translate the templates I need to use wagtail-localize and so my question: Is there a option to not integrate into the page-models?

**Comment by kaedroho** [comment]
@rokondo Wagtail Localize doesn't help with translating templates, you should use [Django for that](https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#internationalization-in-template-code).

You can't use ``wagtail-modeltranslation`` and Wagtail's built-in internationalisation features together, so I'd recommend uninstalling ``wagtail-localize`` and disabling Wagtail's built-in internationalisation.
