### ISSUE TITLE
Linked content in blocks showing only id of the linked content when in translation

### ISSUE THREAD

**Issue by davidbrewer** [wagtail/wagtail-localize#445]
We’ve observed some issues translating content in streamfield blocks. In at least some cases, linked content shows only the id of the linked content, and doesn’t give the ability to edit it. 

For example, here’s an image field on a block in the admin:
![image](https://user-images.githubusercontent.com/218748/129985879-3fb2d84f-917e-4320-bf17-399e12ba3504.png)

But here's what that same image looks like in translation:
![image](https://user-images.githubusercontent.com/218748/129985895-15cb8303-31ee-4305-9111-5bcae539ee39.png)

Here's how the field is defined on the block:
```
  class MyBlock(blocks.StructBlock):
      # other fields...
      image = ImageChooserBlock(required=False)
      # other fields...
```

**Comment by kaedroho** [comment]
We found this occurred when an `ImageChooserBlock` was added into a `StructBlock`

This is now fixed by https://github.com/wagtail/wagtail-localize/pull/480

Thanks for the report!
