### ISSUE TITLE
navigate to the edit page for a translation when clicking "translate this page"

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail-localize#455]
When a user clicks "translate this page" on this screen:

![image](https://user-images.githubusercontent.com/177243/134390963-d118ccc7-736c-49f1-bc61-becf04056dc7.png)

They are asked to indicate which locale the translation is for. Users expect to then be taken to the edit page after picking the locale and clicking "submit", but instead of taken back to the page listing overview, which is super confusing.

Can this behaviour be updated so that after the locale choice is submitted, and wagtail creates a new page, the users is autonavigated to that new page's `edit` URL?

**Comment by zerolab** [comment]
This was fixed by #518
