### ISSUE TITLE
Make it impossible to have two translations into the same locale with duplicated sources

### ISSUE THREAD

**Issue by phildexter** [wagtail/wagtail-localize#462]
(Reported by Twilio) - Add an object ID field to translation and unique constraint.

**Comment by lopenchi** [comment]
Any news about this issue?  cc. @phildexter @kaedroho

**Comment by phildexter** [comment]
Ah thanks for raising this again - we can certainly push this through with the team. We'll get back to you soon!

**Comment by lopenchi** [comment]
Thanks @phildexter ! 
Maybe the "fix" could be **hide** or **disable** the `Translate this page` button when page is not the base one, (Just an idea)

**Comment by lauren-edavey** [comment]
Hey Carolina, we are looking into getting someone on this as soon as possible but we have a few localise experts out at the minute. I will update you early next week with the plan.

**Comment by lauren-edavey** [comment]
Hey @lopenchi - One of our localise experts, Dan should be able to look into this, this afternoon

**Comment by zerolab** [comment]
Hey @lopenchi, I spent some time trying to reproduce this issue with the latest wagtail-localize release and struggle to. See https://youtu.be/Iq9kvjxzPPU

I may have missed something, so do please advise. It is also possible we fixed the issue since in unrelated change 🤔

**Comment by lopenchi** [comment]
Hey @zerolab ! Sorry for late response. 

We just upgrade wagtail-localize to latest version 1.2.1, and the error does not occur anymore :)

**Comment by zerolab** [comment]
Glad to hear it!
