### ISSUE TITLE
Unauthorized PUT request when saving translated string

### ISSUE THREAD

**Issue by davidsevcik** [wagtail/wagtail-localize#497]
Hi all, 
I'm getting 401 Unauthorized server response when trying to save an individual string in Wagtail translation UI

![Screenshot 2021-12-17 at 12 04 05](https://user-images.githubusercontent.com/116192/146536376-c9ea4539-10c3-4843-b692-8346eb6e4cd1.png)

My dependencies:
```
Django==3.2.10
wagtail==2.15.1
wagtail-localize==1.0.1
```

Does anybody else experience this?

**Comment by zerolab** [comment]
The string translation url is an admin URL ([ref](https://github.com/wagtail/wagtail-localize/blob/e782c78fcee5cd85fde5ca8bb3b3c48e857cfda8/wagtail_localize/wagtail_hooks.py#L63))

The view itself should only return a 403 is the requesting user https://github.com/wagtail/wagtail-localize/blob/main/wagtail_localize/views/edit_translation.py#L986-L1040


Is your site (Settings > Sites) properly configured? Do you have some kind of aggressive ad blocker or similar browser extension? Does this work in a different browser at all?

Personally I have not had this issue, be it locally or on a staging or production site

**Comment by hennabanana** [comment]
+1

**Comment by hennabanana** [comment]
Machine Translation works. i compared both requests, in the the `PUT | http://localhost:8000/admin/localize/translate/142/strings/981/edit/` the csrfmiddlewaretoken is missing. But in the Machine Translation PUT it is there.



![Screenshot 2021-12-30 at 10 11 52](https://user-images.githubusercontent.com/25147943/147738123-a465ee21-a483-47f5-a6eb-d3e2925f7da6.png)
![Screenshot 2021-12-30 at 10 11 31](https://user-images.githubusercontent.com/25147943/147738131-651d22fd-e1b2-46a9-9358-296965095afe.png)

**Comment by hennabanana** [comment]
it has to do with the django rest framework, when i comment out the permissions in the settings it works.

`REST_FRAMEWORK = {
    # 'DEFAULT_AUTHENTICATION_CLASSES': (
    #     'rest_framework.authentication.TokenAuthentication',
    #     'rest_framework.authentication.BasicAuthentication',
    # ),
}`

**Comment by zerolab** [comment]
@hennabanana ah! could you maybe give #500 a try?

**Comment by hennabanana** [comment]
@zerolab  https://github.com/wagtail/wagtail-localize/pull/512

**Comment by zerolab** [comment]
Hey everyone,

can you try #513 ?

**Comment by zerolab** [comment]
Fixed in 1cf48a3 + parents
