### ISSUE TITLE
Ability to set DeepL API URL

### ISSUE THREAD

**Issue by raindeer** [wagtail/wagtail-localize#514]
DeepL offers free limited API access with an alternative API URL:
https://api-free.deepl.com/v2/translate vs https://api.deepl.com/v2/translate.

It would be great if one could change the default API URL to the free one. It's great for testing during development etc.

Manually just changing the URL in machine_translators/deepl.py works, so this should be an easy win.

**Comment by zerolab** [comment]
See #505.
The PR needs a couple of tweaks and some tests. If you can help with that, please do

**Comment by vladox** [comment]
@raindeer @zerolab  I'll be working on it tomorrow.

**Comment by zerolab** [comment]
fixed in #604 and will be available in the next release
