### ISSUE TITLE
Clearing optional field in source page keeps translated version which is not editable

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail-localize#524]
Steps to reproduce:

1. Add an optional text field to the page model, e.g. `subtitle = models.CharField(blank=True, max_length=255)`, and migrate the db. Add this field to the template of the page.
2. Create a page in the source language with a subtitle "A"
3. Translate this page and set subtitle to "A (translated)"
4. Remove the source page's subtitle "A"
5. Translate/Sync this page again

The translated page now won't show the subtitle field in the CMS (so it's not translatable), but in the database the subtitle field of this translation is still set! So you cannot change it, but the frontend of the translated page will still show "A (translated)", the frontend of the source page correctly shows no subtitle!

I think similar to how fields only show up if they are not empty in the source object, they should get cleared when the source page's field is cleared.

**Comment by th3hamm0r** [comment]
Recreating the translated page does not work, see https://github.com/wagtail/wagtail-localize/issues/402#issuecomment-1046693788.
Quick-fix for now: You can stop the synced translation, clear the necessary fields in the translated page and then restart the synced translation.

**Comment by zerolab** [comment]
Note that #495 (in latest `main` and shortly in a new release) fixes this particular use case on sync

**Comment by Pomax** [comment]
Note that stopping a synced translation to clear the necessary fields in the translated page is not a realistic option for an organizational site that has 50 users updating hundreds of a pages a day.

**Comment by Pomax** [comment]
@zerolab nice, will that resolve https://github.com/wagtail/wagtail-localize/issues/402#issuecomment-1046693788 as well then?

**Comment by zerolab** [comment]
Looks like it might. It fixes #467 which sound very much like a version of #402.

Am away from computer to check things right now. My plan is to make a new release first thing tomorrow morning

**Comment by zerolab** [comment]
v1.1rc1 is out - https://github.com/wagtail/wagtail-localize/releases/tag/v1.1rc1 -- would appreciate feedback on it, especially around this issue 🙏

**Comment by zerolab** [comment]
Ah, having re-read #402 properly (and not on the go on the phone), we're talking actual deletion of the page/snippet instance, rather than a field. That is not yet sorted.

@th3hamm0r did 1.1rc1 solve this issue?

**Comment by th3hamm0r** [comment]
Yes, this issue has been solved (with https://github.com/wagtail/wagtail-localize/pull/495), thanks!
I've missed #467 during my quick search before I've created this issue, they're actually the same.
