### ISSUE TITLE
Copying page with translatable orderables inside locale throws `IntegrityError`

### ISSUE THREAD

**Issue by marekarendt** [wagtail/wagtail-localize#528]
When we are trying to copy page inside a Locale without `Publish copied page` checkbox the copy is created as draft and when we try to  publish it from page editor form IntegrityError is thrown:

`duplicate key value violates unique constraint "pages_productpagetablehe_translation_key_locale_i_09ba3c17_uniq"
DETAIL:  Key (translation_key, locale_id)=(dc8a9299-2f79-41e3-bf51-2028eb0122e4, 6) already exists.`

 It's related with Orderable items copied with page. Those items inherit from `TranslatableMixin`.  When checkbox is checked, new published page is created and any "publish" or "save" actions don't cause any problems.

**Comment by zerolab** [comment]
@marekarendt what version of Wagtail/wagtail-localize are you using?
Can you add a minimal reproducible code example?

**Comment by marekarendt** [comment]
Django - 3.2.10
Wagtail 2.15.3
Wagtail-localize 1.0.1

`class ContentPage(Page, SectionMixin):
    sections = Page.sections + [SectionMixin]

    content_panels = (
        Page.content_panels
        + [item.panel for item in sections]
    )
`

`class SectionMixin(models.Model):
    class Meta:
        abstract = True

    section_title = models.CharField(max_length=255, blank=True, null=True))
    panel = MultiFieldPanel(
        [
            FieldPanel(field_name='section_title'),
            InlinePanel('section_items', label='Items'),
        ],
        heading='Section',
        classname='collapsible',
    )
`

`class ContentPageItems(TranslatableMixin, Item):
    class Meta(TranslatableMixin.Meta, Item.Meta):
        pass

    page = ParentalKey(ContentPage, on_delete=models.CASCADE, related_name='section_items')
`
`class Item(Orderable, VerboseNamesMixin):
    class Meta:
        abstract = True
        ordering = ['sort_order']

    title = models.CharField(max_length=100)

    panels = [
        FieldPanel('title')
    ]
`

Lets say that those classes reflects our models.

**Comment by zerolab** [comment]
Hey @marekarendt this should be fixed in [2.15.5](https://github.com/wagtail/wagtail/releases/tag/v2.15.5) / [2.16.2](https://github.com/wagtail/wagtail/releases/tag/v2.16.2)

Can you give the new Wagtail release(s) a try?

**Comment by marekarendt** [comment]
Thanks a lot, Im gonna do that. I'll come back with results :)

**Comment by marekarendt** [comment]
Thanks a lot again, it looks like version 2.15.5 helped. From my point of view issue can be closed :)
