### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by Redjam** [wagtail/wagtail-localize#530]
Hi there, 

Many thanks for this awesome work.

I have a small contribution. 

In your documentation https://www.wagtail-localize.org/tutorial/4-templates/, in the example "Adding a language switcher" 
```{{ language_code }}``` should be ```{{ lang.code }}```

Failing to contribute with code, I try to be useful with my limited skills 😅

**Comment by zerolab** [comment]
Thank you @Redjam,

[This should](https://github.com/wagtail/wagtail-localize/blob/main/docs/tutorial/4-templates.md?plain=1#L60) needs updating. Happy to submit a PR. You could go to https://github.com/wagtail/wagtail-localize/edit/main/docs/tutorial/4-templates.md#L60, make the change and submit the PR all via the GitHub interface.

**Comment by Redjam** [comment]
@zerolab thank you for your message! Just did it. This is my first official contribution ever in an open source project 😇

**Comment by zerolab** [comment]
@Redjam can't see the PR, maybe try again?
Also, thank you very much. Welcome to the open source contributors world 👏🏼

**Comment by Redjam** [comment]
@zerolab I think now it's ok

**Comment by zerolab** [comment]
Fixed via #531
