### ISSUE TITLE
Wagtail Localize & FormBuilder: duplicated pages in the admin view

### ISSUE THREAD

**Issue by Redjam** [wagtail/wagtail-localize#539]
Hi there 👋

I'm using Wagtail 2.15.4 with Wagtail Localize 1.0.1. 

I have created a contact page. This page is translated in 4 langages but there is only one contact form. 

In the admin view, I get 4 pages to access the submissions and I think it's not very convenient. See below:

<img width="1254" alt="Capture d’écran 2022-03-11 à 17 14 00" src="https://user-images.githubusercontent.com/6397887/157905586-d7fa2460-ab96-4a74-bc33-92266f8758d8.png">

Is it possible to add a select list of available langages on this page in order to filter by region instead of having the list of all available form pages?

That would be a valuable quick win. Unfortunately I don't know how to do it properly ... 🙈

Later, it could be interesting to think about form submissions. Because even if the page is translated, there is always only one form. Do we need to list all the pages? Won't it be more convenient to list the form and all submissions in the same view which ever the langage?

**Comment by zerolab** [comment]
Wagtail 2.16 fixes that (via https://github.com/wagtail/wagtail/pull/7867)
You can use wagtail-localize 1.1 with Wagtail 2.16
