### ISSUE TITLE
MultipleObjectsReturned - multiple TranslationSource for one translation_key

### ISSUE THREAD

**Issue by hpoul** [wagtail/wagtail-localize#547]
Hello,
I somehow managed to get an inconsistency in my database. When editing a Page I now get the error  `MultipleObjectsReturned` for `TranslationSource` which is called from `wagtail_localize/wagtail_hooks.py` from `ConvertToAliasPageActionMenuItem._is_shown`:

```python
TranslationSource.objects.get(
                        object_id=page.translation_key,
                        specific_content_type=page.content_type_id,
                    ).locale_id
```

What I'm wondering is, whether this is actually valid to have multiple `TranslationSource` for the same `translation_key`? If not it might make sense to add an additional unique index on the database level? right now there is only a unique constraint for `("object", "locale"),` .. maybe it would make more sense to have `("object", "specific_content_type")` as unique constraint, so this error can't occur?

(I think i created the problem by translating a child page from german to english, while the parent page was still a page alias, and not yet translated.. and then somehow managed to accidentally translate this english alias page to english.. which is another problem I guess.. when there is e.g. a german page with an english alias.. the english list would still show the "Translate this page" option in the "More" menu.. which creates a english -> english `Translation` object..)

**Comment by sheralim012** [comment]
There is another way to produce this issue

## Steps to reproduce the issue
- create locales L1, L2, L3
- create a page P1 in locale L1
- translate page P1 to locale L2 (let's say the newly translated page is P1')
- translate page P1' to locale L3 (let's say the newly translated page is P1'')
- delete page P1''
- translation P1 to locale L3
- you will be redirected to edit page with error `MultipleObjectsReturned - get() returned more than one TranslationSource -- it returned 2!`

## Observations
- translation isn't being deleted when deleting the page
- while fetching the translation source multiple translations are matched which results in returning multiple objects

## Possible Solution
- delete the translation while deleting the page
- find some way to uniquely identify the translation source without deleting the invalid translation

CC: @zerolab
