### ISSUE TITLE
Translating draft pages should not automatically make them go live

### ISSUE THREAD

**Issue by olifante** [wagtail/wagtail-localize#553]
When I translate a subtree, all pages in the target locale are shown as Live, losing the distinction in the source subtree between Live and Draft pages. This behaviour feels quite counter-intuitive, and makes it cumbersome to translate large subtrees.

Here's a couple of screenshots illustrating this with a localised version of the Bakery Demo running wagtail-localise 1.1.1:

![Screenshot 2022-04-05 at 17 25 48](https://user-images.githubusercontent.com/5111/161803822-46fcbc52-d7de-4e0e-aca9-951e55c7c770.png)
![Screenshot 2022-04-05 at 17 25 50](https://user-images.githubusercontent.com/5111/161803838-bae934f7-601b-4d4d-a50d-dec3afbfff17.png)

**Comment by zerolab** [comment]
possibly related #511

**Comment by olifante** [comment]
Hey Dan, thanks for looking into this. After reading the discussion in PR #511, this is the same issue that is addressed by that PR.

**Comment by zerolab** [comment]
Fixed in a7b0099 via #511
