### ISSUE TITLE
No fallback using page.localized?

### ISSUE THREAD

**Issue by benjaoming** [wagtail/wagtail-localize#595]
My language switching menu didn't switch language if a translation wasn't available.

I have been displaying a language menu using `{% page_url page.localized %}` where the intended menu link displays the activated language of the loop, i.e..

```html
{% for language_code, language_name in LANGUAGES %}
    {% get_language_info for language_code as lang %}
    {% language language_code %}
        <a  href="{% page_url page.localized %}" rel="alternate" hreflang="{{ language_code }}" title="{{ language_name }}">
            [{{ language_code }}]
        </a>
    {% endlanguage %}
{% endfor %}
```

When there is no translation available for a given language, the link defaults to the English version of the same page. So if a page is only available in English, then all my language switching links will refer to the same English page:

```
[en] [de] [es] <= All links to the same page
```

So I wrote a template tag `page_url_localized_fallback` as a replacement for `page_url` that will keep traversing up the page tree until a page in the target language is found:

```python
@register.simple_tag(takes_context=False)
def page_url_localized_fallback(localized_page, target_language):
    if (
        localized_page.locale.language_code != target_language
        and localized_page.get_parent()
    ):
        return page_url_localized_fallback(
            localized_page.get_parent().localized, target_language
        )
    return localized_page.url
```

If I didn't misunderstand something and the above template tag is necessary, I would like to raise the question: **Is that a good feature for wagtail-localize to ship with?**

Otherwise, please feel free to close the issue :+1:

**Comment by zerolab** [comment]
Hey @benjaoming, this is probably best for core.
I am not sure whether going up the tree until you find a translated page is what most people need. Usually people will switch to a different language to see the same page in that language, not N pages above.

Pehaps you should check that the page has translation (via [`page.has_translation(locale)`](https://github.com/wagtail/wagtail/blob/d40cf331d0151e550b5ea3cea560f5e634da7392/wagtail/models/i18n.py#L199)) and only then provide a working link for that locale (well, language).

**Comment by benjaoming** [comment]
Makes sense that it isn't a template tag for a default case :+1: 

I was looking at a case where there were hundreds of wiki/blog posts and they might be displayed in a non-active language, however the language switcher wasn't working as intended:

> When there is no translation available for a given language, the link defaults to the English version of the same page. 

I guess for someone who wants a different behavior (not traversing up the tree), a different template tag could be built using [page.has_translation(locale)](https://github.com/wagtail/wagtail/blob/d40cf331d0151e550b5ea3cea560f5e634da7392/wagtail/models/i18n.py#L199)
