### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by vmavromatis** [wagtail/wagtail-localize#60]
Hi all, I am running into some installation issues:
1) docs say I should install `'wagtail_localize.workflow',` but it doesn't exist so I had to install `'wagtail_localize.admin.workflow',`
2) I had to install `polib` & `googletrans` manually so as to run the project
3) I update all my existing page models from:
_class HomePage(BootstrapTranslatableMixin,Page):_
Into
_class HomePage(Page):_
and run makemigrations for the appropriate app (in my case home)
then receive this error 
`django.db.migrations.exceptions.InconsistentMigrationHistory: Migration home.0001_initial is applied before its dependency wagtail_localize.0002_initial_data on database 'default'.`

Also, not sure also how to use the BootstrapTranslatableModel operation, something like adding this to migration file 0001_initial?
    operations = [
        BootstrapTranslatableModel('what to put here exactly?'),
    ]

1&2 are ok now, but I would appreciate some help or guidance for 3, thanks!

Regards
Vasilis

**Comment by kaedroho** [comment]
Thanks for trying out wagtail localize, and reporting these issues!

1. This module has been moved on the master branch
2. These should only be required if the google translation/po file modules are enabled. But maybe there is an issue with the readme or something's being imported by mistake somewhere.
3. Not sure what's going on here. Has the `home.0001_initial` migration been changed in any way?

> Also, not sure also how to use the BootstrapTranslatableModel operation, something like adding this to migration file 0001_initial?
> operations = [
> BootstrapTranslatableModel('what to put here exactly?'),
> ]

Documentation is coming for this! The steps are roughly as follows:

 - Add `BootstrapTranslatableMixin` to all models that need to become translatable (same mixin for pages, snippets, child objects)
 - Make a migration
 - Make an empty migration for each app, which runs the `BootstrapTranslatableModel` operation for each model in the app:

```python
operations = [
    BootstrapTranslatableModel('myapp.MyPage'),
    BootstrapTranslatableModel('myapp.MySnippet'),
    ... etc
]

- Then change all the `BootstrapTranslatableMixin` on your models to either `TranslatableMixin` or `TranslatablePageMixin` depending on whether the model is a page model.
- Make another migration
- Migrate

This process is needed to set the `translation_key` field that's added to the model by `TranslatableMixin`/`TranslatablePageMixin`. Django will by default set all your pages to the same translation key, but they need to be unique. You only need to do this for models that have preexisting data.

**Comment by kaedroho** [comment]
This isn't relevant now since Wagtail Localize has been completely rewritten! This particular case should be straightfoward since the fields have been added to ``wagtailcore.Page``
