### ISSUE TITLE
Non-translated (image) fields empty in Pages API

### ISSUE THREAD

**Issue by Timusan** [wagtail/wagtail-localize#608]
When translating using synced translations we have an image field which is not being translated (as it is the same image on all languages):

![image](https://user-images.githubusercontent.com/1012919/187908516-1a143c8d-9593-42f1-a8dd-a4615ad7b7b6.png)

It clearly states that it is using the English version (English is the base language). However, when retrieving this model via Wagtail's Pages API using the locale of the translation the image field is empty. I would expect it to return the english image information.

**Comment by zerolab** [comment]
Hey @Timusan,

any chance you can post a minimal reproducible code sample? including how you're using the API

**Comment by Timusan** [comment]
Hi @zerolab 

Sometimes things resolve themselves overnight ;) This was due to translations which were out of sync which I somehow missed. After syncing them up the image appeared just fine in the API. Sorry for the ticket spam.

**Comment by zerolab** [comment]
Glad it is all sorted. I wonder if there is anything we can do to make this clearer. e.g. a message, or perhapse disable/hide the button 🤔

**Comment by Timusan** [comment]
Hmm, there is a nice message on top of the model ... but I guess it sometimes visually gets lost in the interface ... more of a UX thing. 

On a related note: It is possible to programmatically sync translations on a model?

**Comment by zerolab** [comment]
Sync translations is done via the `UpdateTranslationsView`, specifically https://github.com/wagtail/wagtail-localize/blob/8639e36d5cfe083d03b5fab9462a032facf8effc/wagtail_localize/views/update_translations.py#L129-L159, so you can work something that fits your needs

**Comment by Timusan** [comment]
@zerolab Awesome, thanks for the feedback ;)
