### ISSUE TITLE
update requirements for wagtail > 4.0

### ISSUE THREAD

**Issue by jcuotpc** [wagtail/wagtail-localize#610]
The requirements are set for wagtail < 4.0:

    `install_requires=[
        "Django>=2.2,<4.1",
        "Wagtail>=2.11,<4.0",

        ],`

Is it possible to update the requirements to add wagtail 4.x and django 4.1.x?

**Comment by zerolab** [comment]
#602 will take care of this.

I will realistically have some time to do some maintenance work this Friday afternoon. Hopefully we can get a new release out as well

**Comment by chris48s** [comment]
Note: were going to either want to merge #602 first and then update #589 to bump the wagtail requirement in `pyproject.toml` or merge #589 first and update #602 to account for the fact `setup.py` no longer exists.
