### ISSUE TITLE
Can't update to Django 4.1, neither Wagtail 4.0

### ISSUE THREAD

**Issue by perepicornell** [wagtail/wagtail-localize#619]
I'm updating the project to Django 4.1 and Wagtail 4.0, after seeing in the README that wagtail-localize supports these versions, but I'm getting these errors:

`Because wagtail-localize (1.2.1) depends on Django (>=2.2,<4.1) [...]`
`Because wagtail-localize (1.2.1) depends on Wagtail (>=2.11,<4.0) [...]`

I see that the 1.2.1 [tag](https://github.com/wagtail/wagtail-localize/releases/tag/v1.2.1) dates from January 5th, so I imagine that maybe the `main` branch got updated before a new release, and that's why the readme specifies these compatibilities?

Specifying `1.3alpha1` version it works fine, but I thought you might like to have this reported.

Thanks for the amazing work, take care!

**Comment by zerolab** [comment]
we have https://github.com/wagtail/wagtail-localize/releases/tag/v1.3.0-alpha.3,
and #617 which addresses another issue. Will make another alpha release tomorrow, probably a beta, and if no further issues found will do a full release sometime next week.

Will close this on that basis
