### ISSUE TITLE
Migration fail installing wagtail-localize fresh on a wagtail 4.1 project

### ISSUE THREAD

**Issue by ArnarTumi** [wagtail/wagtail-localize#629]
I was trying to add 1.3a4 to a project that I had already upgraded to wagtail 4, and end up with 
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration wagtailcore.0059_apply_collection_ordering is applied before its dependency wagtail_localize.0001_initial

If I understand this correctly the run_before line in the 0001 migration that was added in #616 will cause a failure for everyone trying to install wagtail-localize after they have already run migrate 0059 (I am at 0076 at the moment)

**Comment by zerolab** [comment]
It is a tough one this one as I keep having a chicken-and-egg issue.
Will take a deeper dive tomorrow. Looks like we need to dig into the migrations state and decide how things are run, because we support 2.15+
