### ISSUE TITLE
docs say 4.0 not yet the case

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail-localize#631]
Wagtail (2.15, 2.16, 3.0, 4.0) with

The docs say this package is compatible with 4.x but this is not yet the case.

**Comment by zerolab** [comment]
The main branch is (with some caveats), have you tried v1.3alpha4 ?

caveats: #630 should fix a case where you add localize to a Wagtail 4 codebase.

**Comment by zerolab** [comment]
Will leave this open as we had the same question popping up in various modes like #619, #614, #610

**Comment by ekersten** [comment]
any ETA on a full release?

**Comment by zerolab** [comment]
Aiming to have a full 1.3 release by the end this Friday.

**Comment by zerolab** [comment]
https://github.com/wagtail/wagtail-localize/releases/tag/v1.3 now available
