### ISSUE TITLE
widget_from_block returns unknown type for ImageChooser/DocumentChooser inside a ListBlock

### ISSUE THREAD

**Issue by spikenn** [wagtail/wagtail-localize#638]
When a `ListBlock` contains an `ImageChooserBlock` or a `DocumentChooserBlock`, function `widget_from_block` returns `{"type": "unknown"}` because `content_components` is `None`

**Model:**
```python
class HomePage(Page):
    body = StreamField(
        [
            ("text", blocks.TextBlock()),
            ("images", blocks.ListBlock(ImageChooserBlock())),
            ("documents", blocks.ListBlock(DocumentChooserBlock())),
        ],
        blank=True,
        null=True,
        use_json_field=True,
    )

    content_panels = Page.content_panels + [
        FieldPanel("body"),
    ]
```

- python 3.9.5
- django 4.1.2
- wagtail 4.0.2
- wagtail-localize 1.3

![Wagtail Admin](https://i.imgur.com/mYLdBRM.png) 

**Possible solution:**
Add an extra elif statement that checks if the block is an instance of a `ListBlock` and `content_components` is `None`:
```python
if isinstance(block, blocks.PageChooserBlock):
    ...
elif isinstance(block, blocks.ListBlock) and content_components is not None:
    return widget_from_block(block.child_block, content_components[1:])
# add this
elif isinstance(block, blocks.ListBlock) and content_components is None:
    return widget_from_block(block.child_block)
```

**Comment by zerolab** [comment]
I would've thought we had this covered by tests. Suppose not.

Will try to make a new patch release in the next 2-3 days. Or happily review a PR
