### ISSUE TITLE
layout isue translate buttons

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail-localize#661]
When translating snippets I see the following small html bug. Seems some container is missing.
Wagtail 4.1 
wagtail-localize==1.3.3

<img width="971" alt="Translation" src="https://user-images.githubusercontent.com/178425/204853293-04f6f5fc-202a-4018-91cc-883bc5eea0c5.png">

**Comment by dassudip2001** [comment]
can I work on this issue

**Comment by zerolab** [comment]
@onno-timmerman I believe the more recent releases fix this

**Comment by zerolab** [comment]
Closing as recent versions of localize fixed this
