### ISSUE TITLE
Can't change images in a translated page, they won't change after select

### ISSUE THREAD

**Issue by pdeero** [wagtail/wagtail-localize#667]
I translated a page from German to English after the translation via deepl, i wanted to modify some image to a english version. In the gif you can see that im choosing an another image and how it's not changing anything after the selection of the new image.

Does somebody has an idea to fix this kind a problem? Thanks in advance.

If more information is needed please let me know.

### requirements.txt
Django==4.1.1
wagtail==4.1.1
wagtail_localize==1.3.3
django-extensions==3.2.0
psycopg2==2.9.3
loglevel==0.1.2
Wand==0.6.10
django-redis==5.2.0
sentry-sdk==1.10.1
wagtail-honeypot==1.0.0

### Used Block:
```
class LinkedImageBlock(BaseLinkBlock):
    image = ImageChooserBlock(required=False)

    class Meta:
        icon = "image"
        template = "blocks/linked_image_block.html"
```

Tested with a fresh database.

![Test](https://user-images.githubusercontent.com/13585685/205882075-6c3e8df6-e9b9-4ea0-bcac-35b19054ee4f.gif)

**Comment by spikenn** [comment]
@pdeero did you collect the static files?
```
python manage.py collectstatic
```

**Comment by pdeero** [comment]
@spikenn YES! It worked thank you very much.
