### ISSUE TITLE
Support Wagtail 4.2 (Current deprecation warnings)

### ISSUE THREAD

**Issue by Timusan** [wagtail/wagtail-localize#674]
The current version of Wagtail Localize uses imports deprecated since Wagtail 4.2:

- importing from `wagtail.core.blocks` has been deprecated in favor of `wagtail.blocks`
- importing from `wagtail.core.models` has been deprecated in favor of `wagtail.models`
- importing from `wagtail.core.rich_text` has been deprecated in favor of `wagtail.rich_text`
- importing from `wagtail.admin.edit_handlers` has been deprecated in favor of `wagtail.admin.panels`
- importing from `wagtail.core.signals` has been deprecated in favor of `wagtail.signals``

This gives a large amount of warnings on startup.
I see a [PR](https://github.com/wagtail/wagtail-localize/pull/673) is underway, did it take this into account as well?

**Comment by zerolab** [comment]
@Timusan #673 will take care of that. e.g. https://github.com/wagtail/wagtail-localize/pull/673/files#diff-169de4ea946b4fae4e8f1f45e566d0b96886b2cf502557b21ae36228db1bf3ceL14

On my list to re-review and get in as soon as possible

**Comment by zerolab** [comment]
Fixed by #673. Release imminent
