### ISSUE TITLE
Locale switcher drop-down partially hidden

### ISSUE THREAD

**Issue by TheoChevalier** [wagtail/wagtail-localize#688]
Hi,

I’ve noticed the locale drop-down menu when editing a page translation is partially hidden behind the .po download button and the promote tab.

<img width="340" alt="Capture d’écran 2023-04-05 à 14 37 46" src="https://user-images.githubusercontent.com/1294206/230875536-d40d0f9b-55c6-4945-8793-949f39b50049.png">

This happens using:
Wagtail: 4.1.3
Wagtail-localize: 1.3.3
Firefox Nightly 113

**Comment by zerolab** [comment]
This is fixed in v1.7
