### ISSUE TITLE
wagtail localize does not support Kurdish and  central Kurdish languages

### ISSUE THREAD

**Issue by farahOueidat** [wagtail/wagtail-localize#695]
To translate the website's content into English, Arabic, and Central Kurdish, I'm using wagtail Localize. While Arabic and English function properly, Central Kurdish redirects to /en/ckb and throws a 404 error. Could you kindly assist me in fixing this problem?

**Comment by zerolab** [comment]
Hi @farahOueidat,

This doesn't enough information for any help. How did you set up your project? Did you follow the instructions on https://www.wagtail-localize.org/tutorial/2-configure-wagtail-localize/ ?

How did you define `WAGTAIL_CONTENT_LANGUAGES`, `LANGUAGES`, the relevant bits for `INSTALLED_APPS`, `MIDDLEWARE`, url patterns?

**Comment by farahOueidat** [comment]
I appreciate your quick reply, 
I did follow the Wagtail localize instructions.
 WAGTAIL_CONTENT_LANGUAGES : 
![Capture1](https://github.com/wagtail/wagtail-localize/assets/26738781/c72c1f39-993b-4214-9dde-9d6bbf8e0a2e)

INSTALLED_APPS
![image](https://github.com/wagtail/wagtail-localize/assets/26738781/083673cb-e4c1-49a5-9d83-9cbc689d8ff8)

MIDDLEWARE
![image](https://github.com/wagtail/wagtail-localize/assets/26738781/8c55b992-3342-4f93-8dba-5039a2d147b1)

url patterns
![image](https://github.com/wagtail/wagtail-localize/assets/26738781/ad10e13a-ae76-4f78-b94e-6542d8dec76c)

**Comment by farahOueidat** [comment]
Django version 4.2 now includes the Central Kurdish (ckb) language, although Wagtail Localize does not support it.

**Comment by zerolab** [comment]
localize 1.5.x supports Django 4.2 with Wagtail 5.0+
