### ISSUE TITLE
Wagtail 5.1 support

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail-localize#708]
- update header to support the new dropdowns (search `c-dropdown t-inverted`, see https://github.com/wagtail/wagtail/blob/dec8ec47ed45560d575d03365ca3198162f171a9/wagtail/admin/templatetags/wagtailadmin_tags.py#L1138-L1142 and https://github.com/wagtail/wagtail/blob/dec8ec47ed45560d575d03365ca3198162f171a9/wagtail/admin/templates/wagtailadmin/shared/dropdown/dropdown.html)

**Comment by kbakk** [comment]
As someone setting up a new Wagtail project - should I downgrade to 5.0? What are the effects of the incompatibilities above?

**Comment by zerolab** [comment]
Hey @kbakk I believe localize works fine on 5.1
This is intended for better/seamless support to make it feel as close to "native" as possible

**Comment by zerolab** [comment]
sorted out in v1.7
