### ISSUE TITLE
Translation buttons showing labels in activated language rather than editor language

### ISSUE THREAD

**Issue by enzedonline** [wagtail/wagtail-localize#719]
Probably related to [Wagtail issue 10962](https://github.com/wagtail/wagtail/issues/10962#issuecomment-1741873284)

Example, editor language English, Django activated language French:
![image](https://github.com/wagtail/wagtail-localize/assets/72310199/b0bcc966-4f7d-4323-a057-8e8399934abc)

And the Delete button:

![image](https://github.com/wagtail/wagtail-localize/assets/72310199/33f3b2be-fbe0-4e44-8db9-b739989a8dfb)

**Comment by zerolab** [comment]
I believe it is indeed

**Comment by zerolab** [comment]
Will close as it is a Wagtail core issue - https://github.com/wagtail/wagtail/issues/10962
