### ISSUE TITLE
TemplateSyntaxError at /admin/locales/

### ISSUE THREAD

**Issue by kltng** [wagtail/wagtail-localize#765]
Hi,

I got the following error when I clicked the **Settings > Locales** in the admin panel.

<div id="summary" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; padding: 10px 20px; margin: 0px; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(221, 221, 221); background: rgb(255, 255, 204);"><h1 style="padding: 0px; margin: 0px; font-weight: normal;">TemplateSyntaxError at /admin/locales/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; word-break: break-word; font-family: sans-serif; color: rgb(87, 87, 87);">Invalid block tag on line 1: 'icon'. Did you forget to register or load this tag?</pre>
Request Method: | GET
-- | --
http://localhost:8000/admin/locales/
4.2.9
TemplateSyntaxError
Invalid block tag on line 1: 'icon'. Did you forget to register or load this tag?
/usr/local/lib/python3.12/site-packages/django/template/base.py, line 568, in invalid_block_tag
wagtail_localize.locales.views.IndexView
/usr/local/bin/python
3.12.1
['/app',  '/usr/local/lib/python312.zip',  '/usr/local/lib/python3.12',  '/usr/local/lib/python3.12/lib-dynload',  '/usr/local/lib/python3.12/site-packages']
Tue, 16 Jan 2024 17:01:27 -0500

</div><div id="traceback" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; padding: 10px 20px; margin: 0px; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(221, 221, 221); background: rgb(238, 238, 238);"><br class="Apple-interchange-newline"></div>

**Comment by zerolab** [comment]
can you please try v1.8-beta.1?

**Comment by zerolab** [comment]
Fixed in v1.8
