### ISSUE TITLE
Multilingual pages are not linked to a site (Wagtail CRX)

### ISSUE THREAD

**Issue by kltng** [wagtail/wagtail-localize#768]
Hi,

I am developing a multilingual site with Wagtail CRX and Wagtail-localize. When I created a new locale and enabled the sync, new home pages in multiple locales were created under "Root" page. However, the newly created page had a message stating: 

**"There is no site set up for this location. Pages created here will not be accessible at any URL until a site is associated with this location. "**

![Screenshot 2024-01-24 at 16 44 20](https://github.com/wagtail/wagtail-localize/assets/15926391/bdb1ee26-b09a-47ae-90ad-10a99dca8206)

I am not sure whether this is a problem with the CRX extension or the wagtail-localize plugin. I would greatly appreciate your suggestions.

**Comment by zerolab** [comment]
Will close this now as there was no follow-up in some time now. Please re-open if it is still an issue
