### ISSUE TITLE
All images are broken on wagtail-localize.org

### ISSUE THREAD

**Issue by atimmer** [wagtail/wagtail-localize#783]
When browsing the documentation of wagtail-localize.org/latest all images are broken. Tested in Safari, Firefox & Chrome.

**Comment by zerolab** [comment]
I am not sure where the issue was, but is seems to be working again.
We're hosting the docs with Read The Docs 🤔

**Comment by atimmer** [comment]
Still broken for me right now:

![C518B99F-72FC-4938-B1ED-44EDCB5CE480](https://github.com/wagtail/wagtail-localize/assets/584693/9d3e893c-ca4f-40e1-8ee8-55c2e6d3fe67)

Not sure what the cause could be. Maybe some weird regional CDN thing? I’m in the Netherlands if that matters.

**Comment by chris48s** [comment]
All images are 404s for me too.

What do you see if you follow this link @zerolab?
https://wagtail-localize.org/_static/tutorial/wagtail-edit-source.png
image or 404 page?

Here's an example curl call if it helps:

```
$ curl "https://wagtail-localize.org/_static/tutorial/wagtail-edit-source.png" -I
HTTP/2 404 
date: Thu, 29 Feb 2024 18:15:33 GMT
content-type: text/html; charset=utf-8
cf-ray: 85d2e4b3d940631d-LHR
cf-cache-status: HIT
age: 46
cache-control: max-age=1200
content-language: en
vary: Accept-Encoding, Accept-Language, Cookie
cdn-cache-control: public
cross-origin-opener-policy: same-origin
referrer-policy: no-referrer-when-downgrade
x-backend: web-i-0f0bddd37a9ad3dc4
x-content-type-options: nosniff
x-rtd-domain: wagtail-localize.org
x-rtd-project: wagtail-localize
x-rtd-project-method: custom_domain
x-rtd-version-method: path
x-served: Proxito-404
server: cloudflare
alt-svc: h3=":443"; ma=86400
```

**Comment by zerolab** [comment]
We're back to normal now. Images were defined as absolute paths, which conflicts with the RTD versioned paths.

**Comment by zerolab** [comment]
Thank you for raising this @atimmer
