### ISSUE TITLE
Crash when using new ImageBlock

### ISSUE THREAD

**Issue by Chadys** [wagtail/wagtail-localize#839]
The new [`ImageBlock`](https://docs.wagtail.org/en/stable/releases/6.3.html#imageblock-with-alt-text-support) is a special kind of `StructBlock`.

The translations of `StreamField` that are using it are crashing.
The first crash that I could raise is on translation sync, line 126 `for field_name, block_value in struct_block.items():` in `wagtail_localize/segments/extract.py` in` handle_struct_block`.

I managed to get around it by using an override of `ImageBlock`:
```python
from wagtail.images.blocks import ImageBlock as WagtailImageBlock
from wagtail_localize.segments import OverridableSegmentValue, StringSegmentValue

class ImageBlock(WagtailImageBlock):
    # because of the special deconstruction of ImageBlock, we need to implements get_translatable_segments

    def get_translatable_segments(self, value: "cms_base.models.CustomImage"):
        if value is None:
            return []
        segments = [
            OverridableSegmentValue("", value.pk),
        ]
        if value.contextual_alt_text is not None:
            segments.append(StringSegmentValue("", value.contextual_alt_text))
        return segments
```

The second crash happened even with the previous hack, when creating a new translation, on line 1544 `blocks_by_id = {block.id: block for block in value}` in `wagtail_localize/models.py` in `get_field_path`; I didn't find any workaround yet.

This issue reference [this one](https://github.com/wagtail/wagtail/issues/12688) on Wagtail. Depending on the fix, it might make sense to be fixed either here or on wagtail's side (maybe even both).

**Comment by zerolab** [comment]
Thank you for raising this. On my radar. some early investigation notes and WIP patch in the [Wagtail Slack](https://wagtailcms.slack.com/archives/CD4S91XF0/p1733932234107819?thread_ts=1733497971.511249&cid=CD4S91XF0)

On my list for some time next week
