### ISSUE TITLE
UpdateTranslationsView is broken

### ISSUE THREAD

**Issue by srtonz** [wagtail/wagtail-localize#845]
The form validation logic in `views.update_translations.UpdateTranslationsView` fails when no machine translators are enabled.

The issue has been introduced in v1.11, specifically in line 159 here - https://github.com/wagtail/wagtail-localize/pull/842/files#diff-7a9a06ed1b48987fdea1654b74e93eaaf519f23c386f682608b2a59ae905d918R159. The key `use_machine_translation` does not necessarily exist on all forms and the check needs to be guarded appropriately.

**Comment by zerolab** [comment]
Thank you for raising this.
https://github.com/wagtail/wagtail-localize/releases/tag/v1.11.1
